### PR TITLE
feat: swap midi for @julusian/midi

### PR DESCRIPTION
**Pull request by Julusian**
I have done a large overhaul of `midi` to make it easier to install and use (no compiling!).
I haven't gotten any response from the maintainers on merging this, so I have published and will be maintaining a fork.

This PR updates easymidi to use my fork, so that users can benefit from the easier install process.
I am aiming for 100% api compatability with `midi` for the current version, so there is little risk to users

### CODE REVIEW

**Comment by dinchak** [comment]
Sounds great, thank you for the PR! I am having some trouble running `npm install`

```
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../vendor/rtmidi/RtMidi.cpp:1543:10: fatal error: alsa/asoundlib.h: No such file or directory
npm ERR!  1543 | #include <alsa/asoundlib.h>
npm ERR!       |          ^~~~~~~~~~~~~~~~~~
npm ERR! compilation terminated.
npm ERR! make: *** [midi.target.mk:120: Release/obj.target/midi/vendor/rtmidi/RtMidi.o] Error 1
```

**Comment by Julusian** [comment]
Strange, it shouldn't need to compile anything..
What os & arch are you using?

Prebuilt binaries are included in the npm package for:
* midi-darwin-arm64  
* midi-darwin-x64  
* midi-linux-arm  
* midi-linux-arm64  
* midi-linux-x64  
* midi-linux-x64-musl  
* midi-win32-ia32  
* midi-win32-x64

**Comment by dinchak** [comment]
Sorry, I haven't used this in awhile and changed environments, need to sort out my dependencies and I'll get back to you!

**Comment by dinchak** [comment]
OK, I think I'm sorted out. I was on OSX when I originally wrote and used this library, I've since switched to Windows.

My original comment I posted was about trouble running `npm install` on WSL2 but that doesn't seem to work with the existing package either, so no worries.

Ran everything successfully on Windows and it seems to work just fine with your fork! Thank you again for the PR! Great to have someone maintaining those midi projects again. Really appreciate it.

**Pull request merged**
