### PR TITLE
Adds support for sending sysex messages.

### PR DESCRIPTION
**Pull request by samhiatt**

### CODE REVIEW

**Comment by dinchak** [comment]
great stuff, thank you sam! will merge and push a new version to npm

**Comment by samhiatt** [comment]
Thanks! I may add some more updates soon.

A quick question: it seems like the bit shifting you do to decode pitch
bend values doesn't work for me. Does it work for your application?

I'd like to make a change so that it works for me, but it would probably
break things for you.

Thanks!

**Comment by dinchak** [comment]
sounds great!

i haven't used the pitch bend functionality much so i wouldn't be surprised if there was a bug with that.  please feel free to make whatever changes you need to get the proper behavior and i'll be happy to merge them! thanks again for the contributions.

**Comment by samhiatt** [comment]
Actually, pitch bend messages seem to be working properly. I was confused
about the range of values they sent, thinking it was the same range as mod
wheel values.

Awesome, thanks! Glad to collaborate. :)

**Comment by dinchak** [comment]
great news! thanks for following up.

**Pull request merged**
